citizensadvice/cads

_data/navigation.yml
assets/css/components/_c--card.scss
assets/css/components/_c--color-block.scss
docs/1.0/foundations/grid.md
docs/1.0/foundations/spacing.md
scss/_cabui.scss
scss/elements/_e--forms.scss
scss/utilities/_u--helpers.scss
scss/utilities/_u--labels.scss

- Update content with examples of grid system.
- Extend color blocks into grid system examples.
- Update spacing docs with correct variable name.

Documentation: Changes to grid content / examples

---

_data/navigation.yml
docs/1.0/foundations/colours.md
docs/1.0/foundations/spacing.md
docs/1.0/foundations/typography.md

Updated text on foundation pages:
Minor text edits on typography, colours and spacing
removed h4-h6 headings o n typography
change xxl to 2xl

minor text amends to foundations

---

assets/css/components/_c--color-block.scss
scss/settings/_s--colors.scss

added turquoise mid in framework and docs

added turquoise mid in framework and docs

---

docs/1.0/foundations/colours.md

added intro line to colour content

content edit to colours

---

docs/1.0/components/section-nav.md

content for section nav

---

_data/navigation.yml
docs/1.0/components/button-groups.md
scss/_cabui.scss
scss/components/_c--button-group.scss

New feature for 'button groups' created to aid tool development.

Feature: Create button groups

---

docs/1.0/components/buttons.md
scss/components/_c--button.scss

- Buttons styling partial required a tidy up to make more consistent.
- Create a new style of button, 'action' buttons specifically for UI's.
- Button spacing and layout also tidied up.

Refactor: Additional button classes and tidy up.

---

scss/elements/_e--forms.scss

Form elements were a little all over the place, this commit refactors
them in order to maintain some consistency.

Refactor: Input consistency

---

_data/navigation.yml
docs/1.0/components/input-fields.md

Changed navigation title from Inputs to Input fields.
Changed URL link title from Inputs to Input fields.

change input title

---

_data/navigation.yml
docs/1.0/components/labels.md
scss/components/_c--form-fieldsets.scss

Also made each `.c-fieldset__item` to be displayed `block` level.

Documentation: Add in label documentation.

---

assets/css/components/_c--highlight.scss
docs/1.0/components/labels.md
docs/1.0/components/radios.md

Include link to label component in radio button pages to give some context.

Documentation: Radio button page changes

---

_data/navigation.yml
docs/1.0/components/date-input.md
docs/1.0/components/form-dateinput.md
scss/components/_c--form-inputs.scss

Create date input component using a combination of other available components.

Feature: Date inputs

---

assets/css/components/_c--card.scss
docs/1.0/foundations/colours.md

Added the colour variables. I had to increase the width of the cards to fit the variable names in. This page maybe something we look to redesign to make the page length shorter. Maybe a table format?

Added colour variables to colour cards

---

scss/components/_c--form-radios-checkboxes.scss

Just changing the padding left and right and font weight.

Updated spacing on radio buttons and checkboxes

---

scss/components/_c--buttons.scss

Changed horizontal padding to spacing-md

Changed horizontal padding on primary button

---

scss/components/_c--section-nav.scss

Changed heading margin bottom to $spacing--xs

updated section-nav spacing

---

site/_layouts/docs.html
site/docs/1.0/assets/scss/components/_c--layout.scss

This is a simple naming convention change.

Refactor: Update layout component with container element

---

scss/_cabui.scss
scss/utilities/_u--line-limit.scss

I'm unsure if I have put this in the right place "utilities". Also do I need to compile the css before pushing the branch?

Created line-width class

---

site/docs/1.0/components/buttons.md

Better guidance around how and when to use button elements over anchor elements.
Resolves #61

Docs: Create further guidance on when to use anchor tags or buttons

---

package.json
sandbox/index.html

Removed http-server module and replaced with more reliable and fuller
featured browser-sync module for better watching and reloading of
files/browser windows.
Resolves #76

Bug: Buggy sandbox environment

---

Makefile
README.md
dockerfile
sandbox/_config.yml
website/_config.yml

Still to do, work out passing variables via docker run to CMD

dockerise app and create Makefile.

---

Makefile

make start will now also run yarn

Makefile update to include yarn command

---

website/src/docs/1.0/components/button-container.md
website/src/docs/1.0/components/buttons.md

Updated the docs as per agreed changes. How the code is shown may need to be reviewed as the they are getting a little long with the inline svgs.

updated buttons doc

---

website/src/_layouts/home.html
website/src/styles/components/_c--hero.scss

Was previously displaying Cabui, now amended.

Documentation: Changes to home page wording

---

website/src/_includes/banner.html
website/src/_layouts/docs.html
website/src/_layouts/wip.html

- Add banner to inform users of out of date docs.
- More detailed homepage of where to available resources.

Chore: Detailing API changes

---

packages/buttons/package.json
packages/core/package.json
packages/radios-checkboxes/package.json
packages/rich-content/package.json
packages/selects/package.json
packages/text-inputs/package.json
packages/validation/package.json

bug [fixing output file names for all broken packages]

---

website/src/docs/1.0/utilities/background-colors.md
website/src/docs/1.0/utilities/text-colors.md

Some markdown tables on documentation site are showing incorrectly.

docs: update markdown tables
